In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import re
import string

In [2]:
df_fake = pd.read_csv('FakeNew.csv')
df_true = pd.read_csv('TrueNew.csv')

In [3]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
df_fake["class"] = 0
df_true["class"] = 1

In [6]:
df_fake.shape , df_true.shape

((23481, 5), (21417, 5))

In [7]:
df_fake_manual_testing = df_fake.tail(10)
for i in range(23480,23470,-1):
    df_fake.drop([i],axis=0,inplace=True)

df_true_manual_testing = df_true.tail(10)
for i in range(21416,21406,-1):
    df_true.drop([i],axis=0,inplace=True)

In [8]:
df_fake.shape , df_true.shape

((23471, 5), (21407, 5))

In [9]:
df_fake_manual_testing.head()
df_true_manual_testing.head()

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1

In [10]:
df_merge = pd.concat([df_fake,df_true],axis=0)
df_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [11]:
df_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='str')

In [12]:
data = df_merge.drop(["title","subject","date"],axis=1)

In [13]:
data.head(10)

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0
5  The number of cases of cops brutalizing and ki...      0
6  Donald Trump spent a good portion of his day a...      0
7  In the wake of yet another court decision that...      0
8  Many people have raised the alarm regarding th...      0
9  Just when you might have thought we d get a br...      0

In [14]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [15]:
data = data.sample(frac=1)
data.head(10)

                                                    text  class
23400  By James PerloffMy friend Rachael McIntosh was...      0
16111  Former acting Attorney General Sally Yates was...      0
18073  RIYADH (Reuters) - Two Saudi guards were shot ...      1
18692  Hilarious conservative media analyst and Youtu...      0
18462  We are so sad to report that Otto Warmbier has...      0
11017  WASHINGTON (Reuters) - Mike Huckabee suspended...      1
18871  ALMATY (Reuters) - The first prominent disside...      1
15638  MOSCOW (Reuters) - Bomb threats forced thousan...      1
13884  If you re wondering about what s happening wit...      0
21999  Jay Dyer 21st Century WireIn the famous treati...      0

In [16]:
data.reset_index(inplace=True)
data.drop(['index'] , axis = 1 , inplace = True)

In [17]:
data.columns

Index(['text', 'class'], dtype='str')

In [18]:
data.head()

                                                text  class
0  By James PerloffMy friend Rachael McIntosh was...      0
1  Former acting Attorney General Sally Yates was...      0
2  RIYADH (Reuters) - Two Saudi guards were shot ...      1
3  Hilarious conservative media analyst and Youtu...      0
4  We are so sad to report that Otto Warmbier has...      0

In [19]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]' , '' , text)
    text = re.sub("\\W" , " ", text)
    text = re.sub('https?://\S+|www\.\S+' , '' , text)
    text = re.sub('<.*?>+' , '' , text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '' , text)
    text = re.sub('\n' , '' , text)
    text = re.sub('\w*\d\w*' , '' , text)
    return text

In [20]:
data['text'] = data['text'].apply(wordopt)

In [21]:
x = data['text']
y = data['class']

In [22]:
x_train , x_test , y_train , y_test = train_test_split(x,y,  test_size = 0.25)

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [24]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train , y_train)

LogisticRegression()

In [25]:
pred_lr = LR.predict(xv_test)

In [26]:
LR.score(xv_test , y_test)

0.9861853832442068

In [27]:
print(classification_report(y_test , pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5909
           1       0.98      0.99      0.99      5311

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [28]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()

In [29]:
DT.fit(xv_train , y_train)

DecisionTreeClassifier()

In [30]:
pred_dt = DT.predict(xv_test)

In [31]:
DT.score(xv_test , y_test)

0.9946524064171123

In [32]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"

def manual_testing(news):
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)

    new_def_test["text"] = new_def_test["text"].apply(wordopt)

    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)

    pred_LR = LR.predict(new_xv_test)

    return print("\nPrediction: {}".format(output_label(pred_LR[0])))

In [33]:
news = str(input())

manual_testing(news)

 try

Prediction: Fake News